### ISSUE TITLE
the superclasses were not considered in the metadata array

### ISSUE THREAD

**Issue by DietrichPaul** [Articdive/ArticData#6]
Example: 
Sheep Entity is missing Health Metadata inherited from packetType LIVING

**Comment by Articdive** [comment]
I'll have a look at this in about a week and I hope to have it finished within a day (next wednesday), I'm currently a bit busy with course work. If you need it earlier you'll need to PR.

**Comment by DietrichPaul** [comment]
Minecraft assembles the DataTracker according to yarn mappings in a initDataTracker method. This can be overridden by other classes. The current method for dumping is to iterate over all fields of the class. But I don't know if the initDataTracker method also adds all these fields... What if a parent class does not call super.initDataTracker()?

**Comment by Articdive** [comment]
> Minecraft assembles the DataTracker according to yarn mappings in a initDataTracker method. This can be overridden by other classes. The current method for dumping is to iterate over all fields of the class. But I don't know if the initDataTracker method also adds all these fields... What if a parent class does not call super.initDataTracker()?

I use a bunch of reflection to get values from the vanilla mappings, in other words, I'm doing a sort of pseduo-static code anaylsis (but in a running JVM, using reflection) to reverse engineer data, it's way more reliable and allows me to reuse generators accross versions, (which also means you know what things Mojang changes in every update :)).

This is now done.
